### ISSUE TITLE
Use AX_PTHREAD to detect POSIX threads compiler options and libraries

### ISSUE THREAD

**Issue by elfring** [michaelrsweet/pappl#112]
Would you like to add the configuration script “[AX_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads")” to [your build specification](https://github.com/michaelrsweet/pappl/blob/62e964494b13b2c6d6ed6ea3d062a56b3f7de532/configure.ac#L116 "Update candidate")?

**Comment by michaelrsweet** [comment]
@elfring I'm not sure that using AX_PTHREAD really adds anything except about 35k to the size of the configure script and support for legacy OS's that I could never test or support. Is there a reason you are suggesting that I use (and need to check/update periodically) that macro?

**Comment by elfring** [comment]
>Is there a reason you are suggesting that I use (and need to check/update periodically) that macro?

Yes, of course.

* This macro is providing known functionality which is helpful for reuse, isn't it?
  (Would you like to avoid code duplication another bit?)
* Can you benefit from [its maintenance](https://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_pthread.m4 "Revision history")?

**Comment by michaelrsweet** [comment]
Since I can’t import the macro directly from its source and since the mechanism it uses to detect pthreads is undocumented “magic”, I’m not keen on switching. Until such time that I have a report of a platform that *I* want to officially support doesn’t work because I have implemented my own POSIX thread checks, and that can only (or best) be fixed by embedding a macro file provided under a more restrictive (GPL3) license into PAPPL, I respectfully will stick with what is already working and under my control.

**Comment by elfring** [comment]
* I do not see “magic” in the mentioned build script.
* It seems that you have got special licence preferences here.
* Would you like to support a software development system like AIX?

**Comment by michaelrsweet** [comment]
@elfring Re: magic, there are a lot of extra checks beyond the compiler and linker options needed for basic POSIX threading support.

GPL3 is poison to any commercial embedded software/hardware distribution, and PAPPL is now being used in *printers* where you can't just install any firmware image you like (for obvious safety/security reasons).

As for AIX, no I have absolutely no interest in supporting or ability to support AIX.
