### ISSUE TITLE
Possible atomicity violations

### ISSUE THREAD

**Issue by ryancaicse** [michaelrsweet/pappl#196]
Hi, in the below code, `system->save_changes = system->config_changes; ` is performed with the condition `system->config_changes > system->save_changes` satisfied. However, the check and write are not atomic. This seems very like a TOCTOU problem([Time-of-check to time-of-use](https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use#:~:text=In%20software%20development%2C%20time%2Dof,the%20results%20of%20that%20check.)). Should it be a bug?

https://github.com/michaelrsweet/pappl/blob/64c978ba3f735c7f7320a5f71e6efd303bcce9ce/pappl/system.c#L610-L623

```
pthread_mutex_lock(&system->config_mutex); 
 if (system->config_changes > system->save_changes) 
    { 
      system->save_changes = system->config_changes; 
  
      if (system->save_cb) 
      { 
        // Save the configuration... 
 (system->save_cb)(system, system->save_cbdata); 
      } 
    } 
pthread_mutex_unlock(&system->config_mutex); 
```

**Comment by michaelrsweet** [comment]
@ryancaicse This code (in `papplSystemRun`) is the only place where we change `save_changes` and runs in its own thread. The mutex only protects the `config_changes` member (which can be updated from any thread that makes a configuration change to the system) and *reading* an integer (for purposes of the comparison) will always be atomic so we don't need to lock the mutex every time through the loop.

The downside of the current implementation is that it is possible for a state save to contain a partial update - there is no notion of grabbing a snapshot of the whole state atomically for performance and memory usage reasons. However, since the mutex makes sure that `config_changes` will be incremented *after* the save callback, another save will be triggered to make sure that the saved state is ultimately "stable".

**Comment by ryancaicse** [comment]
@michaelrsweet OK. Thank you for your detailed reply.
