### ISSUE TITLE
When switching units for custom page sizes, convert the numbers to the new unit

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#200]
I have tested a GIT snapshot of PAPPL some days ago (shortly before 1.2b1 release). There I have especially seen that one can switch the units for the page size (Issue #118) between inches and millimeters now. Thanks for implementing this.

But there is a little issue with it. If you have entered the numbers for the page's dimensions and then switch the unit, the numbers do not change, they are not converted into the new unit. So if you have selected millimeters and enter 254 mm, and then you switch to use inches, you want 10 inches, not 354 inches.

Should be possible to fix it by adding some Javascript.

**Comment by michaelrsweet** [comment]
@tillkamppeter I thought about doing that, but the problem is that if you enter the dimensions first and then realize you have the wrong units, clicking on "mm" or "in" will change the numbers and make them invalid.

Given that the most common use case is that you are entering inches or millimeters and not trying to convert, I'm going to keep things as they are unless we get a lot of users complaining about it...
