### ISSUE TITLE
Switch to a supported localization format

### ISSUE THREAD

**Issue by yarons** [michaelrsweet/pappl#202]
Having a proprietary non-documented localization format requires more work from the translators and prevents them from using standard tools.

Using a well-known and supported format will allow easier localization management and will increase participation in the project.

Translating the file manually is optional but it will be very hard to manage once there will be updates.

I know you've used Gettext PO in CUPS, very good decision.
There are many other supported formats so PO is just a suggestion, this is translate toolkit and the supported formats:
https://github.com/translate/translate

If you'll agree to connect your project to a localization platform such as Weblate (completely open source and offers Libre hosting for open source projects) it's possible to add context to the strings including screenshots etc. to make sure the translators are not confused.

Thank you for your incredible work.

**Comment by michaelrsweet** [comment]
@yarons The .strings format is *not* proprietary, and is the documented format from PWG 5100.13 and NeXTSTEP/OpenSTEP (been around as long as the PO format) that is required for IPP Everywhere and AirPrint, and I’ll note that macOS and iOS applications (free or otherwise) use it exclusively. We’ve been supporting it in CUPS since 2007 where the command localization support uses GNU PO or strings depending on the platform, web localization uses language-specific HTML templates, but printer localization only supports strings files.

WRT Weblate and similar resources, unfortunately my experience has been quite poor, both for CUPS and the PWG’s attribute/value localization resources. I’ve never gotten a single localization that way… :(  But according to the docs, Weblate *does* support strings files…

Anyways, I can’t switch formats. If there are localizers out there that will only work with PO files, I can provide one for PAPPL (converting is trivial - see my [StringsUtil](https://github.com/michaelrsweet/stringsutil) project among others) and convert back when integrating.

**Comment by yarons** [comment]
Consulted Weblate, it is possible apparently, do you have bad experience with Weblate?
Maybe @nijel or @comradekingu can help.

**Comment by nijel** [comment]
Just to clarify - this file is supported by Weblate, see https://docs.weblate.org/en/latest/formats.html#apple-ios-strings. I'm just making some tweaks to make automatic configuration work on this style of repository.

**Comment by yarons** [comment]
Can someone please help @michaelrsweet with Weblate migration? I think this project and CUPS can benefit from such platform.

**Comment by nijel** [comment]
The only tricky thing in importing this into Weblate is [English file](https://github.com/michaelrsweet/pappl/blob/master/pappl/strings/en.strings) which seems to be a corrupted version of [base file](https://github.com/michaelrsweet/pappl/blob/master/pappl/strings/base.strings). I have no clue what are the intentions here, but to me, the safest approach for Weblate seems to ignore it using language filter: `^(?!(en)$).+$`

**Comment by michaelrsweet** [comment]
@nijel Because we are also localizing IPP attribute names and values ("media.na_letter_8.5x11in", "printer-state.3", "media-source.auto", "media-type.auto", etc.) we need the English localization file as well... One side benefit is that we can also differentiate localizations where is makes sense, for example with the "auto" values I listed.

Anyways, I'm trying to add PAPPL to Weblate now but am getting the following error for the file mask when adding a component:

> There is more than one file for English language, please adjust the file mask and use components for translating different resources.

I've move base.strings and ipp.strings to the "pappl" directory, but it still persists in believing that the "pappl/strings/*.strings" file mask shows multiple English strings files...

**Comment by zdohnal** [comment]
@michaelrsweet are you trying to add PAPPL into [Fedora Weblate](https://translate.fedoraproject.org/) or into another Weblate instance, such as [this](https://hosted.weblate.org/) (I've found it by google, I haven't known there is another Weblate instance till today :D ).
I'm asking because Yaron reminded me that I haven't sent email regarding [CUPS localization](https://github.com/OpenPrinting/cups/issues/216) to trans@lists.fedoraproject.org, but now I'm confused whether we all mean the same Weblate instance.

**Comment by nijel** [comment]
That's why I've used the language filter mentioned above: https://github.com/michaelrsweet/pappl/issues/202#issuecomment-1128935236 . The problem is that source language is set to English (so that's what `base.strings` is) and there is also `en.strings`. See https://docs.weblate.org/en/latest/faq.html#what-does-mean-there-are-more-files-for-the-single-language-en for more details.

**Comment by michaelrsweet** [comment]
@zdohnal I went to "weblate.org" and followed the links for the free version to setup a project, so I guess that's the Hosted instance.

@nijel I tried using that filter, and even moved the base.strings and ipp.strings files out of the "strings" subdirectory, but it still insists I have multiple English files... Trying the language filter now...

**Comment by michaelrsweet** [comment]
@nijel ... and that seems to have done the trick.
