### ISSUE TITLE
Support more job attributes

### ISSUE THREAD

**Issue by szlt5** [michaelrsweet/pappl#310]
**Is your feature request related to a problem? Please describe.**

(1) When use "printer-app submit" to submit a file for printing, only several job attributes can be set, such as "page-ranges", "orientation-requested". Is it possible to support more attributes, such as: "page-set", "outpputoder", and "number-up".
- The list of "page-set-supported" can be "odd,even,all".
- The list of "outputorder-supported" can be "reverse,normal".
- The list of "number-up-supported" can be "1,2,3,6,9,16"

(2) When submit a file, the "job-sheets" attribute can be set, but the list of the "job-sheets-supported" is "none". Is It possible to expand the list of the "job-sheet-support" as "none,classified,confidential,form,secret,standard,topsecret,unclassified"?

**Comment by szlt5** [comment]
Just saw the https://github.com/michaelrsweet/pappl/issues/227, please ignore the request (2) about the "job-sheets-supported".

**Comment by michaelrsweet** [comment]
"page-set" isn't a standard IPP attribute, and at the moment isn't something that I'll be bringing over from CUPS 2.x. A printer application's driver can, of course, add it as a vendor option. If we were standardizing this attribute we'd likely need to change the name since "set" has a different meaning for IPP - "set" is the collection of pages grouped for copies/finishing...

"outputorder" isn't a standard IPP attribute, either. The corresponding IPP attribute would be "page-delivery" - that likewise isn't currently supported (requires a lot of processing to be done to the input) but might come over as part of issue #308.

"number-up" is also something that would come over with issue #308.
