### ISSUE TITLE
Add accessor functions to printer and job IPP attributes in printer and job data structures

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#41]
**Is your feature request related to a problem? Please describe.**
I am currently working on a Printer Application for PostScript printers. It should support all PostScript printers which simply work with CUPS due to having a manufacturer-supplied PPD file and the Snap also should contain all PPDs which are free software and were included with Linux distributions.
For that I have created libppd in cups-filters for handling collections of PPDs finding the correct one for a discovered printer and letting jobs output in PostScript format with the appropriate code snippets of the PPDs (especially of the user-settable options) inserted.
Now for handling a job I create a PAPPL filter which loads the PPD assigned to the printer, creates the list of PPD options and choices appropriate to the job's IPP attributes and the printer's defaults and then call an appropriate filter function of libcupsfilters.
To easily turn printer and job IPP attributes into the corresponding PPD option settings I have created the function ppdGetOptions() (in libppd, based on the get_options() function of CUPS' ippeveps.c) which takes the printer and job IPP attributes (a pointer to the whole structure) and the PPD file.I want to call theis function from my PAPPL filter but I cannot access the printer and job IPP attributes as the internal structures of pappl_printer_t and papple_job_t are not in the public API and there are also no accessor functions.
For the jobs one can also grab a single attribute when one knows its name, but I need the whole set of IPP job attributes to pass it on to the ppdGetOptions() function.
This is probably also useful for many other Printer Applications, especially non-raster ones.

**Describe the solution you'd like**
What I need are accessor functions which return a pointer to the job attributes and to the printer attributes, like for example:
```
ipp_t *pappleJobGetAttrs(pappl_job_t *job)
{
  return job->attrs;
}

ipp_t *papplePrinterGetAttrs(pappl_printer_t *printer)
{
  return printer->attrs;
}
```

**Describe alternatives you've considered**
Any solution with the existing API would be awkward, as one had to "translate" the PPD into the printer IPP attributes with each job and after that derive the possible job IPP attribute names out of the printer IPP attributes and after that poll the job's IPP attributes with each of the possible job attribute names using papplJobGetAttribute(). Adding the extra accessor functions to PAPPL is trivial and makes the implementation of the PostScript Printer Application easy.

As I am in the middle of creating the PostScript Printer Application and I am planning to create several other very similar ones (Foomatic for the Ghostscript built-in drivers and most other classic drivers, PCL XL, retro-fit of proprietary drivers, ...) I am very grateful if you could do this simple, trivial API addition quickly.

**Comment by michaelrsweet** [comment]
@tillkamppeter The printer capability attributes should be straight-forward enough to return (papplPrinterGetDriverAttributes), although I'm not sure what benefit that will have once you have already set the PPD-sourced attributes in your driver callback. It might be better to simply add a driver data pointer to the pappl_pdriver_data_t structure so that you can persist data for each printer.

As for the job attributes, I fail to see why you'd need them when you can access named attributes. Don't expect to support arbitrary PPD options as IPP attributes - that's just not going to work with IPP Everywhere/AirPrint clients, so the focus should be on mapping the standard attributes to the (non-standard) PPD options.

**Comment by michaelrsweet** [comment]
@tillkamppeter OK I've pushed some changes to add an "extension" field to the printer driver data structure, along with a new "delete" function so you can store additional driver data for a printer.

There is also a new papplPrinterGetDriverAttributes function for getting the printer attributes.

**Comment by tillkamppeter** [comment]
Thanks for the explanations and additions.
You have added a function papplPrinterGetDriverAtributes(), but it should read papplPrinterGetDriverAt**t**ributes(). In general, it is also inconsistent to have a function papplPrinterGet**Driver**Attributes() and papplPrinterGet**PrintDriver**Data(). Could you correct these two points?

**Comment by tillkamppeter** [comment]
In the driver callback I source the PPD attributes using the ppdLoadAttributes() function of libppd of cups-filters. The resulting pointer I drop in the driver_attrs pointer supplied from the caller of the callback. I assume that this pointer in driver_attrs ends up as the driver_attrs field of the _pappl_printer_s structure for the printer and this way can be grabbed in the a job filter by the papplPrinterGetDriverAtributes() function. Am I right?

**Comment by michaelrsweet** [comment]
@tillkamppeter Re: papplPrinterGet/SetPrintDriverData, I had changed the names when we thought we might add scan and fax directly in PAPPL, but right now I don't see that as likely. I'll rename things back which will trigger a lot of code changes elsewhere (in hp-printer-app, the gutenprint work, etc.)

Re: the attributes passed to papplPrinterSetPrintDriverData vs. papplPrinterGetDriverAttributes, what you get will be a superset of the attributes you provide since PAPPL takes care of generating all of the standard attributes.

**Comment by tillkamppeter** [comment]
@michaelrsweet does this mean that there will not get added Scan/Fax support to PAPPL any more? Is this not in the works by a student currently? Or did he come witha very different approach?

**Comment by michaelrsweet** [comment]
@tillkamppeter FaxOut could potentially still be added, but the number of MFPs with "PC Fax" support is exceedingly small and fax is only becoming less and less relevant.

The current scan situation points to implementing eSCL and not IPP Scan in the printer application, since eSCL is the "standard" for network scanning. There are no IPP Scan clients aside from what might exist inside SANE. Both eSCL and IPP Scan can be implemented using PAPPL resource callbacks.

So my focus for PAPPL is to make sure that we have printing covered. If scanning can be added, great, but that's isn't the focus for 1.0.

**Comment by michaelrsweet** [comment]
Closing now that this is implemented.
