### ISSUE TITLE
If a driver is removed/renamed on an update it should not cause a fatal error

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#87]
**Describe the bug**
If during the development of a Printer Application driver names get changed the Printer Application will not start up with the state file of the previous version. A printer with a driver name which does not exist causes a fatal error.

A "normal" user does not know what is going on.

**To Reproduce**
Start an arbitrary Printer Application and create a printer. Then stop the Printer Application.

Either
- Edit the printer entry in the state file, modifying the driver name to a non-existing one.

Or
- Edit the source code of your Printer Application, modifying the name of the driver you have used for your printer, rebuild.

Now start the Printer Application again. It will error out and not keep running. You can only make the Printer Application start again if you undo the above step or edit the state file removing the offending printer entry.

**Expected behavior**
The Printer Application starts up normally, with some useful treatment of the offending printer:
- The auto-add callback is performed on the printer to automatically find the best replacement under the currently available drivers (no re-discovery of the printer required, the device ID is saved in the state file). **This is the solution I recommend.**
- The Printer Application is started regardless of the missing driver but the printer is stopped, to conserve its job history at least. The web interface should offer to change the driver manually.
- The Printer is deleted. **BAD: The job history gets lost.**

**Comment by tillkamppeter** [comment]
Very important is that there should never be caused a fatal error by the content of the state file, as otherwise it is a big problem for non-programming-aware users.

**Comment by michaelrsweet** [comment]
@tillkamppeter I definitely want to address this, but this shouldn't be a common occurrence. I think all we can do is try the auto-add callback if the named driver doesn't exist, as a backup. And if no matching driver can be found, delete/drop the printer.

**Comment by michaelrsweet** [comment]
@tillkamppeter After thinking about this for a bit, a printer application can do the auto-detect stuff in its driver callback, and if it has a bad/unknown driver name then "do the right thing" by auto-detecting or using a generic driver of some sort. The only thing it can't do is pause the printer (because the printer is in the process of being created), and honestly since there is no way to change the driver after creating the printer there is no way to "recover" if the driver is truly gone. Moreover, the job history is very limited (on purpose) and I don't want to special-case supporting a non-working printer that cannot be resumed and does not have any of the required attributes for a printer.

So, what I'm going to do for this is:

1. Update papplSystemLoadState to not error-out/crash on a broken printer, but to gracefully continue with the bad printer dropped.
2. Update the documentation to make it clear that this is the expected behavior and what a developer can do in their driver callback to deal with any errors.

**Comment by michaelrsweet** [comment]
[master e716d24] Fix crashes when loading state, and document expected behavior (Issue #87)
